[workspace]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "An example of using the Mojo testing framework"
name = "testing"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
main = "mojo run src/example.mojo"
test_dec = "mojo run -I src test/my_math/test_dec.mojo"
test_inc = "mojo run -I src test/my_math/test_inc.mojo"
test = { depends-on = ["test_dec", "test_inc"] }

[dependencies]
mojo = "<1.0.0"
