[project]
name = "Mojo GPU block and warp operation examples"
version = "0.1.0"
description = "Examples of Mojo GPU block and warp operations"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[dependencies]
mojo = "<1.0.0"

[tasks]
tiled_matmul = "mojo run tiled_matmul.mojo"
