[workspace]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Examples of using the LayoutTensor struct"
name = "LayoutTensor examples"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
mojo = "<1.0.0"

[tasks]
layout_tensor = "mojo run layout_tensor_examples.mojo"
layout_tensor_gpu = "mojo run layout_tensor_gpu_examples.mojo"
layout_tensor_all = "mojo run layout_tensor_examples.mojo && mojo run layout_tensor_gpu_examples.mojo"
